apiVersion: v1
kind: Service
metadata:
  name: clinic-rest
  labels:
    app: clinic-rest
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: 8080
    - name: https
      port: 9191
      targetPort: 8080
  selector:
    app: clinic-rest
