apiVersion: v1
kind: Service
metadata:
  name: clinic-domain
  labels:
    app: clinic-domain
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8181
  selector:
    app: clinic-domain
