apiVersion: v1
kind: Service
metadata:
  name: clinic-webapp
  labels:
    app: clinic-webapp
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8181
  selector:
    app: clinic-webapp
