apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-domain
  labels:
    app: clinic-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-domain
  template:
    metadata:
      labels:
        app: clinic-domain
    spec:
      restartPolicy: Always
      containers:
        - name: clinic-domain
          image: cs548/clinic-domain
          env:
            - name: DATABASE_PASSWORD
              value: YYYYYY
          imagePullPolicy: Never
