kind: Deployment
apiVersion: apps/v1
metadata:
  name: cs548db
  labels:
    app: cs548db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs548db
  template:
    metadata:
      labels:
        app: cs548db
    spec:
      restartPolicy: Always
      containers:
        - name: cs548db
          image: cs548/database
          env:
            - name: POSTGRES_PASSWORD
              value: XXXXXX
            - name: DATABASE_PASSWORD
              value: YYYYYY
          imagePullPolicy: Never
