apiVersion: v1
kind: Service
metadata:
  name: cs548db
  labels:
    app: cs548db
spec:
  type: NodePort
  ports:
    - name: jdbc
      port: 5432
      targetPort: 5432
  selector:
    app: cs548db
